import { PresetScenario } from '../types';

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'golfball-storm',
    nameKo: '강력한 뇌우 (골프공 우박)',
    badgeKo: '경보급',
    descriptionKo: '강한 상승기류(38m/s), 높은 습도(85%), 윈드시어(18m/s)로 4~5cm 크기의 파괴적인 골프공급 우박이 성장합니다.',
    iconName: 'CloudLightning',
    params: {
      surfaceTemp: 27,
      cloudTopTemp: -48,
      freezingLevel: 3.0,
      cloudTopAltitude: 13.0,
      relativeHumidity: 85,
      supercooledWater: 3.5,
      updraftVelocity: 38,
      horizontalWindSpeed: 18,
      turbulence: 3,
      surfacePressure: 1008,
      iceNucleiDensity: 'normal',
      initialEmbryoSizeMm: 2,
    },
  },
  {
    id: 'supercell-giant',
    nameKo: '슈퍼셀 폭풍 (야구공 거대 우박)',
    badgeKo: '재난급',
    descriptionKo: '초저기압(992hPa)과 초강력 상승기류(52m/s), 95% 극고습도 조건에서 8cm 이상의 거대 우박이 다중 순환하여 수박을 연속 격파합니다.',
    iconName: 'Zap',
    params: {
      surfaceTemp: 29,
      cloudTopTemp: -58,
      freezingLevel: 2.8,
      cloudTopAltitude: 15.5,
      relativeHumidity: 95,
      supercooledWater: 4.8,
      updraftVelocity: 52,
      horizontalWindSpeed: 28,
      turbulence: 4,
      surfacePressure: 992,
      iceNucleiDensity: 'low',
      initialEmbryoSizeMm: 3,
    },
  },
  {
    id: 'summer-shower-melted',
    nameKo: '한여름 소나기 (지상 융해 / 비)',
    badgeKo: '우박 소멸',
    descriptionKo: '상층에서 작은 우박이 생기지만 높은 지상 기온(34°C)과 고온 다습한 공기로 낙하 중 전부 녹아 소나기로 변합니다.',
    iconName: 'CloudRain',
    params: {
      surfaceTemp: 34,
      cloudTopTemp: -30,
      freezingLevel: 4.2,
      cloudTopAltitude: 10.0,
      relativeHumidity: 70,
      supercooledWater: 2.0,
      updraftVelocity: 18,
      horizontalWindSpeed: 10,
      turbulence: 2,
      surfacePressure: 1012,
      iceNucleiDensity: 'high',
      initialEmbryoSizeMm: 1.5,
    },
  },
  {
    id: 'early-summer-marble',
    nameKo: '초여름 돌풍 (동전·구슬 우박)',
    badgeKo: '주의보',
    descriptionKo: '상층 한기 유입으로 0℃ 동결선이 낮아져 1.5~2cm 크기의 단단한 동전 크기 우박이 쏟아져 농작물에 피해를 줍니다.',
    iconName: 'CloudHail',
    params: {
      surfaceTemp: 22,
      cloudTopTemp: -42,
      freezingLevel: 2.2,
      cloudTopAltitude: 11.5,
      relativeHumidity: 78,
      supercooledWater: 2.6,
      updraftVelocity: 26,
      horizontalWindSpeed: 15,
      turbulence: 3,
      surfacePressure: 1014,
      iceNucleiDensity: 'normal',
      initialEmbryoSizeMm: 2,
    },
  },
  {
    id: 'spring-graupel',
    nameKo: '봄철 건조 돌풍 (싸락눈 다수)',
    badgeKo: '미세 우박',
    descriptionKo: '낮은 습도(45%)와 많은 빙결핵으로 수분이 분산되어 쌀알 크기의 백색 불투명 싸락눈(Graupel, 저밀도)이 생성됩니다.',
    iconName: 'Snowflake',
    params: {
      surfaceTemp: 16,
      cloudTopTemp: -35,
      freezingLevel: 1.8,
      cloudTopAltitude: 9.0,
      relativeHumidity: 45,
      supercooledWater: 1.1,
      updraftVelocity: 16,
      horizontalWindSpeed: 12,
      turbulence: 2,
      surfacePressure: 1020,
      iceNucleiDensity: 'high',
      initialEmbryoSizeMm: 1.0,
    },
  },
];
